
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setText("Banking System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 240, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 190, 40);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel3.setText("Account Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 170, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel4.setText("Transaction Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 190, 23);

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel5.setText("Transaction Description");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 260, 23);

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel6.setText("Deposit");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 140, 23);

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel7.setText("Withdraw");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 150, 23);

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel8.setText("Balance");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 380, 100, 20);

        tf1.setEditable(false);
        tf1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tf1.setText("10110");
        getContentPane().add(tf1);
        tf1.setBounds(320, 70, 450, 29);

        tf2.setEditable(false);
        tf2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tf2.setText("Admin");
        getContentPane().add(tf2);
        tf2.setBounds(320, 120, 450, 29);

        tf3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(tf3);
        tf3.setBounds(320, 170, 450, 29);

        tf4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(tf4);
        tf4.setBounds(320, 220, 470, 50);

        tf5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(tf5);
        tf5.setBounds(320, 280, 460, 29);

        tf6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(tf6);
        tf6.setBounds(320, 320, 460, 29);

        tf7.setEditable(false);
        tf7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(tf7);
        tf7.setBounds(320, 370, 460, 29);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        rb1.setText("Deposit");
        getContentPane().add(rb1);
        rb1.setBounds(40, 410, 150, 31);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        rb2.setText("Withdraw");
        getContentPane().add(rb2);
        rb2.setBounds(40, 450, 130, 31);

        jButton1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 420, 120, 50);

        jButton2.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton2.setText("Balance");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 420, 140, 50);

        jButton3.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 420, 101, 50);

        jButton4.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(710, 420, 83, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(rb1.isSelected())
        {
        String a;
        a = "10110";
        tf1.setText(a);
        String b;
        b= "Admin";
        tf2.setText(b);
        String c=tf3.getText();
        String d=tf4.getText();
        String e1=tf5.getText();
        String f=tf6.getText();
        f=null;
        //String g=tf7.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javamicro","root","");
            String query = "insert into banking values('"+a+"','"+b+"','"+c+"','"+d+"','"+e1+"','"+f+"');";
            Statement s=(Statement) con.createStatement();
            int success;
            success = s.executeUpdate(query);
            if(success==1)
            {
                JOptionPane.showMessageDialog(this,"Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Problem in Saving, Retry");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        
        else
        {
            String a;
        a = "10110";
        tf1.setText(a);
        String b;
        b= "Admin";
        tf2.setText(b);
        String c=tf3.getText();
        String d=tf4.getText();
        String e1=tf5.getText();
        e1=null;
        String f=tf6.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javamicro","root","");
            String query = "insert into banking values('"+a+"','"+b+"','"+c+"','"+d+"','"+e1+"','"+f+"');";
            Statement s=(Statement) con.createStatement();
            int success;
            success = s.executeUpdate(query);
            if(success==1)
            {
                JOptionPane.showMessageDialog(this,"Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Problem in Saving, Retry");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            tf3.setText("");
            tf4.setText("");
            String a=tf1.getText();
            a="10110";
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javamicro","root","");
                    Statement s=(Statement) con.createStatement();
                    String query="Select acnumb, acname, sum(deposit) as deposit_sum, sum(withdraw) as withdraw_sum, "
                            + "sum(deposit) - sum(withdraw) "
                            + "as balance_amt from banking where acnumb = '"+a+"';";
                    ResultSet rs = s.executeQuery(query);
                    while(rs.next())
                    {
                        tf5.setText(rs.getString("deposit_sum"));
                        tf6.setText(rs.getString("withdraw_sum"));
                        tf7.setText(rs.getString("balance_amt"));
                    }
                }
                catch(ClassNotFoundException | SQLException | HeadlessException e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        tf6.setText("");
        tf7.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    // End of variables declaration//GEN-END:variables
}
